<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Documents\Handlers\" />
    <Folder Include="Indexing\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SearchEngine.Domain\SearchEngine.Domain.csproj" />
  </ItemGroup>

</Project>
